apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cnoe-ref-impl
  region: eu-north-1
  version: "1.31"
managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      role: general-purpose
iam:
  withOIDC: true
addons:
- name: aws-ebs-csi-driver
  version: "v1.31.0-eksbuild.1"
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy