---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-config
    creationPolicy: Owner
  data:
    - secretKey: KC_HOSTNAME
      remoteRef:
        key: cnoe/keycloak
        property: KC_HOSTNAME
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: cnoe/keycloak
        property: KEYCLOAK_ADMIN_PASSWORD

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: postgresql-config
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: cnoe/keycloak
        property: POSTGRES_DB
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cnoe/keycloak
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: cnoe/keycloak
        property: POSTGRES_USER
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-user-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-user-config
    creationPolicy: Owner
  data:
    - secretKey: user1-password
      remoteRef:
        key: cnoe/keycloak
        property: user1-password
